oldschoolgg/oldschooljs

src/structures/Items.ts

-   Infernal max cape have the Duplicate item as the lower ID, so people can't equip it.
-   Added itemID 21284 to the USELESS_ITEMS array.

Fixes infernal max cape

---

src/meta/types.ts
src/structures/Items.ts

-   Icon was already being set by item fetch, it was just missing on the item Type
-   Add a new property, `custom`, that will be automatically set when custom items are created.
-   Add property `custom?: boolean;`
-   Add property `icon?: string;`

Add two new optional properties to the Item type, custom and icon

---

src/structures/Items.ts

-   ItemID 0 was being sent back by Items.get as undefined
-   Changes the check to allow ID 0

Dont treat itemID 0 as undefined anymore

---

src/simulation/clues/Elite.ts

-   The Monocle is currently not possible to be obtained through Elite Clue Caskets. This should be a possible reward.
-   Fixes https://github.com/oldschoolgg/oldschoolbot/issues/1026 and fixes https://github.com/oldschoolgg/oldschoolbot/issues/950.
-   Adds Monocle to the Elite Clue Casket loot table.

Add Monocle to Elite Clue Loot Table

---

src/simulation/monsters/bosses/Vorkath.ts
src/simulation/monsters/bosses/Zulrah.ts
src/simulation/monsters/special/Barrows.ts

-   Refactorings to Zulrah, Vorkath to bring their unique drops in line with the LootTable update. Closes oldschoolgg/oldschoolbot#915
-   Refactorings to Barrows, updating Barrows from a Monster to SimpleMonster. resolves oldschoolgg/oldschoolbot#866
-   Create tertiary LootTable for Zulrah
-   Create tertiary LootTable for Vorkath
-   Combine normal LootTable with the tertiary table for a total monster drop table without affecting kill results.
-   Change Barrows from Monster to SimpleMonster
-   Add table property to barrows
-   Combine unique and other drops LootTables for a total barrows drop table without affecting kill results. 

Loot table refactoring

---

src/simulation/monsters/bosses/slayer/AlchemicalHydra.ts
src/simulation/monsters/low/a-f/FossilIslandWyvernAncient.ts
src/simulation/monsters/low/a-f/FossilIslandWyvernLongTailed.ts
src/simulation/monsters/low/a-f/FossilIslandWyvernSpitting.ts
src/simulation/monsters/low/a-f/FossilIslandWyvernTaloned.ts
src/simulation/monsters/low/g-m/IceTroll.ts
src/simulation/monsters/low/g-m/MithrilDragon.ts
src/simulation/monsters/low/n-s/SmokeDevil.ts
src/simulation/monsters/low/t-z/UndeadCow.ts

Fixed drop tables on the following monsters:
Ice Trolls
Undead cow
Fossil island wyverns (added missing seaweed spores and made minor fixes to the rest of the  table)

Fix drop tables on various monsters

---

src/simulation/monsters/bosses/slayer/AlchemicalHydra.ts
src/simulation/monsters/bosses/slayer/ThermonuclearSmokeDevil.ts
src/simulation/monsters/low/a-f/CrawlingHand.ts
src/simulation/monsters/low/a-f/Drake.ts
src/simulation/monsters/low/g-m/Hydra.ts
src/simulation/monsters/low/t-z/Wyrm.ts

Fix regular hydra tables, as well as thermy.
/edit: Fixed hydra + boss hydra drop tables the right way.
Drop rates were incorrect on regular hydra's on-task table
Minor adjustment to rates on both on+off task hydra to match game more closely
Added Jar of smoke to thermy

Thermy + regular hydra drop tables

---

src/constants.ts

Phosani's nightmare was recently added to the hiscores breaking the Hiscores and thus the tests.
-   Added Phosani's nightmare to the list of bosses

Fix tests by adding missing boss to hiscores

---

src/util/util.ts

-   Ancient shards drop at 2x the rate than they should compared to in game. This corrects that. Checked the math against about 10 monsters, it checks out.

Correct ancient shard drop rate to in game values

---

src/structures/Monster.ts

-  Adds plural aliases to any monster that doesn't have one defined already. Fixes slayer blocks showing "Black demons" but not having the plural demons as an alias, but for all monsters.

Add plurals to monster aliases

---

src/structures/LootTable.ts

If limit is below total weight, items become silently unobtainable or lower drop rate (depending on if the limit is partially or fully exceeded)

Loot table limit error throw

---

src/simulation/monsters/low/g-m/Lobstrosity.ts

Lobstrosity table is incorrect, this fixes it.
Fixed drop rate of noted herbs.
Fixed drop rate of seaweed spores

Fix Lobstrosity table

---

src/simulation/monsters/low/g-m/Gargoyle.ts
src/structures/SimpleMonster.ts

-   Refactor the way superiors and brittle keys are dropped from the SimpleMonster.kill() function.
Linked to OSB: https://github.com/oldschoolgg/oldschoolbot/pull/2278
-   Superiors are now calculated in OSB and not in OSJS
-   Brittle key is now on the task-only table of Gargoyles instead of in the kill() function

Refactor the SimpleMonster.kill() drops the right way

---

src/simulation/misc/Zalcano.ts
src/simulation/monsters/bosses/KrilTsutsaroth.ts
src/simulation/monsters/bosses/Skotizo.ts
src/simulation/monsters/bosses/slayer/AbyssalSire.ts
src/simulation/monsters/bosses/slayer/Cerberus.ts
src/simulation/monsters/low/a-f/AbyssalDemon.ts
src/simulation/monsters/low/a-f/BlackDemon.ts
src/simulation/monsters/low/a-f/Bloodveld.ts
src/simulation/monsters/low/a-f/DemonicGorilla.ts
src/simulation/monsters/low/g-m/GreaterDemon.ts
src/simulation/monsters/low/g-m/GreaterNechryael.ts
src/simulation/monsters/low/g-m/Hellhound.ts
src/simulation/monsters/low/g-m/Imp.ts
src/simulation/monsters/low/g-m/LesserDemon.ts
src/simulation/monsters/low/g-m/MutatedBloodveld.ts
src/simulation/monsters/low/n-s/Nechryael.ts
src/simulation/monsters/low/n-s/Pyrefiend.ts
src/simulation/monsters/low/n-s/Pyrelord.ts
src/simulation/monsters/low/t-z/Waterfiend.ts
src/simulation/monsters/superiorMonsters/FlamingPyrelord.ts
src/simulation/monsters/superiorMonsters/GreaterAbyssalDemon.ts
src/simulation/monsters/superiorMonsters/InsatiableBloodveld.ts
src/simulation/monsters/superiorMonsters/InsatiableMutatedBloodveld.ts
src/simulation/monsters/superiorMonsters/Nechryarch.ts

Add the demonic ashes to the loot tables of relevant monsters based on wiki drop tables.
-  Add Fiendish ashes to Imp, Pyrefiend, Pyrelord, Waterfiend and Flaming Pyrelord
-  Add Vile ashes to Bloodveld, Greater Demon, Hellhound, Lesser Demon, Mutated Bloodveld, Insatiable Bloodveld and Insatiable Mutated Bloodveld.
-  Add Malicious ashes to Kril minions, Black Demon, Demonic Gorilla, Greater Nechryael, Nechryael and Nechryarch.
-  Add Abyssal ashes to Abyssal Sire, Abyssal Demon and Greater Abyssal Demon.
-  Add Infernal ashes to Kril, Zalcano, Skotizo and Cerberus.

Add demonic ashes to simulations

---

src/simulation/clues/Elite.ts

-   Currently, the elite clue drop table is not consistent with OSRS as it does not include the mega rare table buff from Poll 76. The tweet from Mod Ash below explains how they implemented the buff in-game. This yields a 3rd age chance per roll of 1/14,662.5 despite the poll promising 1/13750. The relevant wiki page is also included below.
https://twitter.com/JagexAsh/status/1529773495588208641
https://oldschool.runescape.wiki/w/Reward_casket_(elite)#Mega_rare_table_-_Elite_clues
-   Changed the mega rare table chance within the elite rare table to 2/51 from 1/50 (consistent with OSRS).

Update elite clue mega rare chance

---

src/meta/types.ts

The bossRecords interface is missing a few boss fields. I added the missing ones with their names taken from `mappedBossNames`.
Added these records to the bossRecords interface
- phosanisNightmare
- tempoross
- theatreofBloodHard
- tombsofAmascut
- tombsofAmascutExpert

Add missing bossRecords

---

src/simulation/monsters/low/n-s/Rogue.ts

According to the Oldschool RuneScape wiki, Rogue [drops (1)](https://oldschool.runescape.wiki/w/Rogue#Weaponry) Iron dagger(p), and not (9).
This fixes issue #309 
- Rogue will now drop (1) Iron dagger(p)

Fix drop table for Rogue

---

src/simulation/monsters/bosses/Skotizo.ts

Following the successful osrs poll, updates the jar of darkness to the correct rate.
https://secure.runescape.com/m=poll/oldschool/results?id=1649
(This will stay in draft until the change is live in game)

Update jar of darkness rate

---

scripts/prepareItems.ts

-  Updates prepareItems so that the 'deteledItems' shown match the difference between the previous and newly generated item_data.json

Fix Deleted items in the prepareItems script

---

src/simulation/openables/Implings.ts

Following the recent update in osrs adds 3 ring of recoils to the drop table of magpie implings.
Sources - https://oldschool.runescape.wiki/w/Magpie_impling_jar
https://secure.runescape.com/m=news/even-more-poll-78-changes?oldschool=1

Add ring of recoils to Magpie Implings

---

src/simulation/monsters/bosses/Vorkath.ts
src/simulation/monsters/low/a-f/BabyBlackDragon.ts
src/simulation/monsters/low/a-f/BabyBlueDragon.ts
src/simulation/monsters/low/a-f/BlueDragon.ts
src/simulation/monsters/low/a-f/BrutalBlueDragon.ts

Now we have the item update, adds the scaly blue dragonhide to the drop tables - https://oldschool.runescape.wiki/w/Scaly_blue_dragonhide
Will do a separate pr to open them 

Add Scaly blue dragonhide to drop tables

---

src/simulation/monsters/bosses/DukeSucellus.ts
src/simulation/monsters/bosses/TheLeviathan.ts
src/simulation/monsters/bosses/TheWhisperer.ts
src/simulation/monsters/bosses/Vardorvis.ts

Works in tandem with the following pr: https://github.com/oldschoolgg/oldschoolbot/pull/5443
Removes tablets from DT2 boss loot tables and allows https://github.com/oldschoolgg/oldschoolbot/pull/5443 to handle the tablets to prevent dupes from taking up loot rolls.

Remove tablets from DT2 bosses

---

src/constants.ts
src/meta/types.ts
src/simulation/openables/BonusOpenables.ts
src/simulation/openables/BrimstoneChest.ts
src/simulation/openables/LarransChest.ts

Updates the code for Larran's and Brimstone chest to properly calculate and give fish based on the users fishing level.
- "If one lands the 1/20 chance to hit the fish drop table, sequential rolls are made until one succeeds, starting with raw manta rays and ending with raw lobsters in case all rolls fail." - osrs wiki Fish drop table
- Update Larran's Big and small chest
- Update Brimstone chest 
- Update FishTable (formerly BonusOpenables) with proper quantities, remove skill and weight.
- Add chanceOfFish function that uses skilling success rate formula from ingame.
- Rework the code to implement the in-game Fish drop table.
- Add scurrius to fix failing tests
- Supports: https://github.com/oldschoolgg/oldschoolbot/pull/5426
- Works in tandem with: …

Larran's & Brimstone chest fish

---

scripts/prepare.ts
scripts/prepareItems.ts
src/structures/Items.ts
test/items.sanity.test.ts

-   Removes nearly 600 individual clue-step items (All named `Clue scroll (easy/beginner/medium/hard/elite/master)`)
-   Adds regex to filter out the ~600 clue-step items mentioned above.
-   Adds some items to USELESS_ITEMS array that weren't caught by the filter
-   Adds `DO_NOT_REMOVE` variable to prevent removal of critical items.

Remove clue step items & show deleted + added items

---

src/meta/types.ts
src/simulation/monsters/bosses/Bryophyta.ts
src/simulation/monsters/low/g-m/MossGiant.ts
src/structures/LootTable.ts

- Update mossy key & add a new option to .tertiary()
- Remove the averaged mossy key rate since https://github.com/oldschoolgg/oldschoolbot/pull/5426 will handle it properly.
- Add `freeze?: boolean;` to LootTableMoreOptions. This will prevent unintentional items from having their drop chance manipulated such as being on a moss giant task (which increases mossy key drop rate by 66.67% for moss giants) and killing bryophyta which shouldn't have it's mossy key drop chance altered regardless of slayer task.

Mossy key fixes

---

src/simulation/monsters/low/g-m/MithrilDragon.ts

Adds ancient page drops to mithril dragons
- Add note drops to mithril dragons
- Remove an extra coins drop (the second coin drop is replaced with dragon javelin heads upon completion of MM2, so only one of these should drop)
addresses part of: https://github.com/oldschoolgg/oldschoolbot/issues/6000

Add ancient page drops to mithril dragons

---

src/simulation/monsters/low/t-z/TormentedDemon.ts

- Fix the logic for synapse and claw
- "Roll 1/500 for the tormented synapse drop. If unsuccessful, roll for a burning claw drop".
- Make synapse and claw .oneIn 500 in their correct order
- This doesn't contain any of the `yarn dev` file changes

Tormented demon unique drops fix

---

src/simulation/monsters/bosses/Araxxor.ts

- added Elite clues to Araxxor drop table
- added Elite clues to Araxxor drop table
closes: https://github.com/oldschoolgg/oldschoolbot/issues/6094

add Elite clues to Araxxor
