- src/util.ts
- test/Util.ts
Negative numbers weren't being converted properly before. This PR fixes that and adds tests to assert it works correctly.
> add ability to convert negative numbers to k/m/b + tests

- src/monsters/Zulrah.ts
[wolf confirming](https://twitter.com/Jay_Wilton/status/1111946035604176897)
> zulrah: combine flax and mutagen roll

- src/monsters/FixedAllotmentSeedTable.ts
- src/monsters/Guard.ts
- src/monsters/index.ts
- test/Monsters.ts
clue chance is increased from falador diary
> Monsters: add guards

- src/constants.ts
Added Nightmare to the constant list for the hiscore pulled data. Tried it locally and thought id suggest add.
> Nightmare Highscore Added

- src/simulation/clues/Hard.ts
Should be dropping amulet of glory (t4) instead of amulet of glory(t)
> fixed to drop the correct kind of glory (t)

- src/simulation/openables/MysteryBox.ts
missed this in my previous run through of updating drop tables
> openables: update mystery box with new data

- src/data/monsters_data.json
- src/simulation/monsters/bosses/Sarachnis.ts
- src/simulation/monsters/index.ts
- yarn.lock
Added Sarachnis loot table
Added Sarachnis loot table
> Add Sarachnis V2

- package.json
- src/simulation/misc/Nightmare.ts
> fix nightmare quantity

- src/simulation/monsters/bosses/Sarachnis.ts
- yarn.lock
Had forgotten a few minor details on the drop table that I now added.
Had forgotten a few minor details on the drop table that I now added.
> Sarachnis fix Loot table

- package.json
- src/index.ts
- src/structures/Bank.ts
- test/Bank.ts
- test/BankClass.ts
- test/Hiscores.ts
- test/Items.ts
- test/Monsters.ts
- test/News.ts
- test/Polls.ts
- test/Util.ts
- test/Wiki.ts
- test/Worlds.ts
- test/suite.ts
> add bank class

- README.md
- scripts/prepareItems.ts
- src/meta/types.ts
- src/structures/Items.ts
- test/Items.ts
- test/Monsters.ts
> item refactor

- src/simulation/misc/Zalcano.ts
- src/simulation/misc/index.ts
> add zalcano

- src/structures/Bank.ts
- test/BankClass.test.ts
> implement bank.has

- src/simulation/openables/GiantEggSacFull.ts
- src/simulation/openables/index.ts
Added Giant egg sac(full) to openables.
Added Giant egg sac(full) to openables.
> GiantEggSacFull

- src/simulation/monsters/low/Imp.ts
Added white and yellow beard to imp loot table
Added white and yellow beard to imp loot table
> Fix Imp Loot Table

- src/simulation/minigames/ChambersOfXeric.ts
> Fix olmlet

- src/index.ts
- src/simulation/minigames/ChambersOfXeric.ts
- src/simulation/monsters/special/Barrows.ts
- src/simulation/monsters/special/Hespori.ts
- src/simulation/monsters/special/TzTokJad.ts
- src/simulation/openables/BrimstoneChest.ts
- src/simulation/openables/LarransChest.ts
- src/simulation/openables/SeedPack.ts
- src/structures/Bank.ts
- src/structures/LootTable.ts
- src/structures/Monster.ts
- src/structures/SimpleMonster.ts
- test/BankClass.test.ts
- test/Monsters.test.ts
- test/testUtil.ts
> refactor loottables to use banks

- src/simulation/monsters/low/a-f/Ankou.ts
- src/simulation/monsters/low/g-m/Minotaur.ts
-   Skull halves now drop from Ankous and Minotaurs.
> Skull halves

- src/simulation/openables/Implings.ts
- src/simulation/openables/index.ts
> add implings

- scripts/prepareItems.ts
- src/meta/types.ts
- src/util/index.ts
- src/util/weirdItemFilter.ts
- test/Items.test.ts
> Reduce size of item data file by 3x (remove lots of items,etc)

- scripts/prepareItems.ts
- test/Hiscores.test.ts
> add new items

- package.json
- src/structures/Bank.ts
- test/Bank.test.ts
> v2.1.3 - ability to freeze banks

- src/simulation/monsters/low/a-f/Catablepon.ts
Update the Catablepon drop table to include the Tertiary clue scroll medium drops
> Update Catablepon Table

- src/simulation/misc/Nightmare.ts
Update the coins drop on phosani and regular nightmare tables to match in game
> Nightmare coin drop fix

- scripts/prepareItems.ts
-   Re-implements the OSRS Wiki GE prices
- Implements the osrs rswiki's GE price API
**NOTE: You must run t he prepareItems script to generate the new prices**
> Put back RS Wiki GE prices

- src/constants.ts
- src/meta/types.ts
- src/util/util.ts
- test/Hiscores.test.ts
Adds the guardians of the rift to the hiscores
> Add rifts closed to hiscores

- src/simulation/misc/GrandHallowedCoffin.ts
Add the tertiary drop of the clue scroll elite to sepulchre
> Add clue scroll elite - Sepulchre

- src/structures/Bank.ts
- test/Raids.test.ts
> Optimize bank.remove()

- src/constants.ts
Adds tombs of amascut to the hiscores
> Add tombs of amascut to hiscores

- src/simulation/monsters/bosses/Skotizo.ts
Adds the ensouled demon head and totem piece drops to the skotizo table.
Closes https://github.com/oldschoolgg/oldschoolbot/issues/4137
> Update skotizo table

- src/simulation/misc/Nightmare.ts
Closes https://github.com/oldschoolgg/oldschoolbot/issues/4433
As per the wiki - https://oldschool.runescape.wiki/w/Phosani%27s_Nightmare#Consumables
> Update phosani zamorakian brews drop

- src/simulation/monsters/low/n-s/SkeletonMage.ts
Updates the skeleton mage drop table to be accurate to the wiki - https://oldschool.runescape.wiki/w/Skeleton_Mage
> Update Skeleton mage drop table

- src/simulation/openables/GrubbyChest.ts
- test/Hiscores.test.ts
As per the wiki update the tables on grubby chest - https://oldschool.runescape.wiki/w/Grubby_Chest
> Update Grubby Chest Tables

- src/meta/types.ts
- src/simulation/monsters/special/Barrows.ts
- src/structures/LootTable.ts
- src/structures/SimpleMonster.ts
> Loot table roll options

- src/constants.ts
- src/meta/types.ts
- src/util/util.ts
- test/Hiscores.test.ts
Updates highscore test for Sol Heredit, Lunar Chests, Colosseum Glory.
- Add B0aty as a new user to check legacy bountyhunter and colosseum scores
> Update Hiscore test

- src/simulation/monsters/low/n-s/SpiritualMageZaros.ts
- src/simulation/monsters/low/n-s/SpiritualRangerZaros.ts
- src/simulation/monsters/low/n-s/SpiritualWarriorZaros.ts
Adds the drop tables for the zaros variants of the spiritual mager, ranger and warriors.
> Add Zaros Spiritual Creatures

- src/simulation/monsters/bosses/wildy/Callisto.ts
- src/simulation/monsters/bosses/wildy/ChaosElemental.ts
- src/simulation/monsters/bosses/wildy/Scorpia.ts
- src/simulation/monsters/bosses/wildy/Spindel.ts
- src/simulation/monsters/bosses/wildy/Venenatis.ts
- src/simulation/monsters/bosses/wildy/Vetion.ts
- src/simulation/monsters/low/g-m/LavaDragon.ts
- src/simulation/openables/MuddyChest.ts
As per poll 80, update the wildy boss tables to the correct loot tables Source - https://oldschool.runescape.wiki/w/Update:Poll_80_Wilderness_Changes_%26_More
> Update Wildy Boss tables

- src/simulation/monsters/bosses/wildy/Scorpia.ts
> Fix Scorpia drop table

- src/simulation/monsters/low/g-m/LizardmanShaman.ts
Updates the dwh droprate to 1/3000 as per the recent osrs update https://oldschool.runescape.wiki/w/Update:Project_Rebalance:_Combat_Changes
> Update dwh droprate

- src/simulation/misc/Nightmare.ts
Updates the nightmare unique drop rates as per the recent osrs update https://oldschool.runescape.wiki/w/Update:Project_Rebalance:_Combat_Changes
> Update nightmare droprates

- src/simulation/monsters/low/a-f/Crab.ts
- Fix Crab table :crab: 
- Corrected drop table for crab.
- I didn't update anything under `yarn dev`
> Fix crab table
